-- UniTrade OAU Supabase schema
create extension if not exists "pgcrypto";

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  oau_email text not null unique check (oau_email ilike '%@oauife.edu.ng'),
  department text not null,
  access_status text not null default 'pending' check (access_status in ('pending', 'approved')),
  created_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  price numeric(12,2) not null check (price >= 0),
  description text,
  category_id bigint not null references public.categories(id) on update cascade on delete restrict,
  seller_id uuid not null references public.users(id) on update cascade on delete restrict,
  image_url text not null,
  status text not null default 'available' check (status in ('available', 'sold')),
  created_at timestamptz not null default now()
);

create index if not exists idx_products_category_id on public.products(category_id);
create index if not exists idx_products_seller_id on public.products(seller_id);
create index if not exists idx_products_status_created_at on public.products(status, created_at desc);

insert into public.categories (name)
values ('Textbooks'), ('Hostel Gear'), ('Electronics'), ('Fashion')
on conflict (name) do nothing;

alter table public.users enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;

-- Public read access for categories and available products.
create policy if not exists "Public can read categories"
  on public.categories for select
  using (true);

create policy if not exists "Public can read available products"
  on public.products for select
  using (status = 'available');

-- App backend (service role) bypasses RLS. These policies support anon/authenticated reads and authenticated writes if needed.
create policy if not exists "Authenticated can insert access requests"
  on public.users for insert
  with check (access_status = 'pending');

create policy if not exists "Authenticated can insert products"
  on public.products for insert
  with check (true);
